name: MLflow Workflow

on:
  push:
    branches:
      - main

jobs:
  mlflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn

      - name: Run MLflow script
        run: |
          python training.py
