name: MLflow Workflow

on:
  push:
    branches:
      - main

jobs:
  mlflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Adjust as needed
      - name: docker login
        env: 
          DOCKER_USER:  ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow scikit-learn

      - name: Run MLflow script
        run: |
          python training.py
      
      - name: Build the Docker image
        run: docker build . --file model-training/Dockerfile --tag abwqr/test-model:v1
